- clean: ['~']

- link:
    ~/.config/kitty: kitty
    ~/.config/ranger/rc.conf: ranger.conf
    ~/.config/yakuakerc: yakuakerc
    ~/.config/nvim: nvim
    ~/.local/share/kxmlgui5/okular/part.rc: okular
    ~/.scripts:
      create: true
      path: scripts
    ~/.zshrc: zshrc

- create:
    - ~/scripts
    - ~/repos
    - ~/.local/share/kxmlgui5/okular

- shell:
  - [git submodule update --init --recursive, Installing submodules]
