- defaults:
    link:
      relink: true

- clean: ["~", "~/.config", "~/.local/share"]

- create:
    - ~/scripts
    - ~/repos
    - ~/.local/src

- shell:
    - ["git submodule update --init --recursive", Installing submodules]

- link:
    ~/.config/kitty: kitty
    ~/.config/nvim: nvim
    ~/.config/ranger: ranger
    ~/.zsh_plugins.txt: zsh_plugins.txt
    ~/.zshrc: zshrc
    ~/.scripts:
      create: true
      path: scripts

- shell:
    - [
        "sh .dotbot_scripts/install_plugin_managers.sh",
        Installing neovim & ZSH plugin managers,
      ]
    - ["nvim +PlugUpdate +PlugClean! +qa", Installing neovim plugins]
    - ["touch ~/.zshrc_local", Touched ~/.zshrc_local file]
    - ["zsh", Installing zsh plugins]
