- clean: ['~']

- link:
    ~/.config/kitty: kitty
    ~/.config/ranger/rc.conf: ranger.conf
    ~/.config/yakuakerc: yakuakerc
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.scripts:
      create: true
      path: scripts
    ~/.zshrc: zshrc

- create:
    - ~/scripts
    - ~/repos

- shell:
  - [git submodule update --init --recursive, Installing submodules]
