- clean: ['~']

- create:
    - ~/scripts
    - ~/repos
    - ~/.local/share/kxmlgui5/okular

- link:
    ~/.config/kitty: kitty
    ~/.config/ranger: ranger
    ~/.config/yakuakerc: yakuakerc
    ~/.config/nvim: nvim
    ~/.local/share/kxmlgui5/okular/part.rc: okular
    ~/.scripts:
      create: true
      path: scripts
    ~/.zshrc: zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - ['sh ~/.scripts/install_plugin_managers.sh', Installing neovim & ZSH plugin managers]
  - ['nvim +PlugUpdate +PlugClean! +qa', Installing neovim plugins]
  - ['zsh', Installing zsh plugins]
