set -g default-terminal xterm-256color
set -as terminal-overrides ',*:Tc'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Reload bind
unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on
set -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
set-option -sg escape-time 10

set -g history-limit 9999999
set-option -g status-position top

set-option -g focus-events on
set-option -g default-terminal "xterm-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'wfxr/tmux-net-speed'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g @tmux_power_theme 'everforest'
set -g @tmux_power_status_interval 1
set -g @tmux_power_right_arrow_icon ''
set -g @tmux_power_left_arrow_icon  ''
set -g @tmux_power_left_a  ' #{USER}@#h'
set -g @tmux_power_left_b  ' #S'
set -g @tmux_power_left_c  ''
set -g @tmux_power_left_d  ''
set -g @tmux_power_right_w '󰕒#{upload_speed} 󰇚#{download_speed}'
set -g @tmux_power_right_x '#{cpu_fg_color}󰍛 #{cpu_percentage} #{ram_fg_color} #{ram_percentage} #{gpu_fg_color}󰢮 #{gpu_percentage} #{gram_fg_color} #{gram_percentage}'
set -g @tmux_power_right_y ' %T'
set -g @tmux_power_right_z ' %F'

set -g @cpu_percentage_format "%3.0f%%"
set -g @ram_percentage_format "%3.0f%%"
set -g @gpu_percentage_format "%3.0f%%"
set -g @gram_percentage_format "%3.0f%%"
# set -g @cpu_percentage_format "%2.0f%%"

set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding
set -g @tmux_navigator_bind_backslash 'false'

bind C-l send-keys 'C-l'
bind C-\\ send-keys 'C-\' # '

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
#-#-# start_of_ranger_tmux_config #-#-#
bind-key Bspace run-shell -b '/usr/bin/python -m ranger_tmux.drop'
#-#-# end_of_ranger_tmux_config #-#-#
